spring:
  application:
    name: item-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/item-server/templates/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 4444