spring:
  application:
    name: user-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/user-server/templates/
  datasource:
    url: jdbc:mysql://localhost:3306/equipme_user_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 2222