spring:
  application:
    name: user-service
  freemarker:
    enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/user-server/templates/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

server:
  port: 2222